version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: nesta-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nesta
      POSTGRES_USER: nesta_admin
      POSTGRES_PASSWORD: letmein
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
